site_name: IT 304 Assignment 2

theme:
  name: material
  icon:
    logo: material/radar
  palette:
    primary: custom
  features:
    - navigation.path
    - navigation.top
    - toc.follow

nav:
  - Home: index.md


extra:
  generator: false
  homepage: 

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2024 Me All Rights Reserved.
