site_name: IT 304 Assignment 2

theme:
  name: material
  palette:
    primary: black
    scheme: slate
  features:
    - navigation.top
    - navigation.tabs
    

nav:
  - Home: index.md
  - Ethics: ethics.md


