site_name: RADAR Documentation

theme:
  name: material
  icon:
    logo: material/radar
  palette:
    primary: custom
  features:
    - navigation.path
    - navigation.top
    - toc.follow

nav:
  - Home: index.md
  - 'User Guide': 
    - 'Setup Guide': setup.md
    - 'Sign-In Instructions': sign-in.md
    - 'Dashboard Overview': dashboard.md
    - 'Navigating the Interface': navigation.md
    - 'Discussion Features': discussion.md
  - 'Penetration Tests': 
    - 'Request a Pentest': request-pentest.md
    - 'Types of Pentests': pentest-type.md
    - 'My Pentests': my-pentest.md
  - 'Threat Discovery':
    - 'Threat Discovery': threat-discovery.md
    - ' Discovery Configuration': configuration.md
    - 'Authentication Methods': auth-method.md
  - 'Settings': settings.md


extra:
  generator: false
  homepage: https://radarsecurity.ai

extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2024 <a href="https://www.riscpoint.com/">RISCPoint<sup>&reg;</sup></a> All Rights Reserved.
